# Generated by Django 4.1.5 on 2023-01-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_taskmanager', '0002_remove_task_images_delete_image_task_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tasks/', verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(blank=True, to='to_do_taskmanager.image'),
        ),
    ]
