# Generated by Django 4.1.5 on 2023-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_taskmanager', '0003_image_remove_task_images_task_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='task',
            name='images',
            field=models.ImageField(blank=True, upload_to='tasks/'),
        ),
    ]
